### ISSUE TITLE
Problems setting up a federation

### ISSUE THREAD

**Issue by nicoleharris** [GEANT/met#26]
I've set up a new federation - OpenAthens - within MET.  It appears in the list but the metadata won't load to the database...gets to a count of 1033 out of 1072 and freezes.

**Comment by biancini** [comment]
The problem was related to this issue of cryptography lib:
https://github.com/pyca/cryptography/issues/3160
as it seems the new OID "1.3.14.3.2.29" (sha1RSA, used in OpenAthens by some entity) was not supported in the version of the library we were using.
Updated the library the federation updated process worked fine.
