### ISSUE TITLE
as of Feb12, 2018, met Tool may have stale eduGAIN data?

### ISSUE THREAD

**Issue by canariecaf** [GEANT/met#37]
As of Feb 12, 11:45ET the entity: https://compass.astm.org/sp/shibboleth 

is being reported as 'present' in eduGAIN when it is not according to technical.edugain.org as seen in screenshots below.

A RFE it would be very handy to see the last time an given aggregate was refreshed on the federation summary page such as 'FedName (updated: xhrs ago)'

I know latency is possible and am ok with it but maybe there's a delayed job or refreshes are aged out?

![image](https://user-images.githubusercontent.com/5281413/36108146-1c1bcce0-0fea-11e8-91d9-742e46177c10.png)

![image](https://user-images.githubusercontent.com/5281413/36108189-38f08d2e-0fea-11e8-9820-40d60107f22f.png)
![image](https://user-images.githubusercontent.com/5281413/36108234-55e0d79a-0fea-11e8-8590-b8a080fcfd97.png)

**Comment by biancini** [comment]
Processing metadata for all federations is quite a long job for the online app.
That's the main reason why MET, since its conception, processes new versions of metadata files in batch during the night (in the morning time in CET).

Now, without any intervention, I see MET correctly reports "https://compass.astm.org/sp/shibboleth" as not being part of eduGAIN.

Regarding an information about registration time, in the Federation view MET shows last update date.
We could add a specification about the time of last update, so the information is more visible.
We can also add the "update time" information also to each entity.

A patch will follow. After this patch I will close this issue.
Thanks,
